version: '3'
services:
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile
    image: testingwordcount:v1
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "7077:7077"   # Spark master port (leave unchanged)
      - "8085:8081"   # Spark master UI
    networks:
      - spark-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 10s
      timeout: 5s
      retries: 5

  spark-worker-1:
    image: testingwordcount:v1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - spark-net

  spark-worker-2:
    image: testingwordcount:v1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - spark-net

  spark-worker-3:
    image: testingwordcount:v1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - spark-net

  spark-submit:
    image: testingwordcount:v1
    container_name: spark-submit
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
      - spark-worker-3
    volumes:
      - ./dst:/opt/bitnami/spark/docker-spark/dst
      - /Users/macbookpro_2015/dev/python/learningSpark/docker-spark/opt/spark-data/largeFileWordCount.py:/opt/spark-data/largeFileWordCount.py
    command: >
      spark-submit
      --master spark://spark-master:7077
      --deploy-mode client
      /opt/spark-data/largeFileWordCount.py
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge

#docker exec -it spark-master spark-submit --master spark://spark-master:7077 --deploy-mode client /opt/bitnami/spark/imageWordCount.py
#/opt/spark-data/largeFileWordCount:
#  py:
